# -*- coding: utf-8 -*-
"""4_DT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIpK5cVA6tbv2PTtxzhGFZotJs7qZ6d_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data=pd.read_csv("SeoulBikeData.csv",encoding='latin1')

data.head()

data.columns

data.info()

data.shape

data.isnull().sum()

data['Date'] = pd.to_datetime(data['Date'], dayfirst=True)

data['Day'] = data['Date'].dt.day
data['Month'] = data['Date'].dt.month
data['Year'] = data['Date'].dt.year
data['Weekday'] = data['Date'].dt.weekday

data.drop('Date', axis=1, inplace=True)

le = LabelEncoder()

data['Seasons'] = le.fit_transform(data['Seasons'])
data['Holiday'] = le.fit_transform(data['Holiday'])
data['Functioning Day'] = le.fit_transform(data['Functioning Day'])

data.corr()['Rented Bike Count']

X = data.drop('Rented Bike Count', axis=1)
y = data['Rented Bike Count']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

dt=DecisionTreeRegressor(max_depth=5,random_state=42)
dt.fit(X_train,y_train)

y_pred_test=dt.predict(X_test)
y_pred_train=dt.predict(X_train)
r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

# n and p
n_train, p = X_train.shape
n_test = X_test.shape[0]

# Adjusted R2
adj_r2_train = 1 - (1 - r2_train) * (n_train - 1) / (n_train - p - 1)
adj_r2_test = 1 - (1 - r2_test) * (n_test - 1) / (n_test - p - 1)
print("R² Score (Decision Tree - Train set):", r2_train)
print("R² Score (Decision Tree - Test set):", r2_test)
print("Adjusted R² (Decision Tree - Train set):", adj_r2_train)
print("Adjusted R² (Decision Tree - Test set):", adj_r2_test)

leaf_nodes=dt.apply(X_train)

# Map each leaf to the datapoint indices it contains
leaf_to_points = {}
for idx, leaf in enumerate(leaf_nodes):
    leaf_to_points.setdefault(leaf, []).append(idx)

print("Total number of leaves:", len(leaf_to_points))

print("Leaf-wise data point count:")
for leaf_id, indices in leaf_to_points.items():
    print(f"Leaf {leaf_id}: {len(indices)} data points")

import optuna
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tqdm import tqdm

def adjusted_r2(r2, n, p):
    return 1 - (1 - r2) * (n - 1) / (n - p - 1)

def build_model(optimizer="adam", activation="relu", hidden_layers=1, units=64):
    model = keras.Sequential()
    for _ in range(hidden_layers):
        if activation == "leakyrelu":
            model.add(layers.Dense(units))
            model.add(layers.LeakyReLU(negative_slope=0.1))
        else:
            model.add(layers.Dense(units, activation=activation))
    model.add(layers.Dense(1))  # output for regression
    model.compile(optimizer=optimizer, loss="mse")
    return model

def train_nn_leaf(X_leaf, y_leaf, n_trials=30):

    def objective(trial):
        model = build_model(
            optimizer=trial.suggest_categorical(
                "optimizer", ["adam", "adamw", "rmsprop", "nadam"]
            ),
            activation=trial.suggest_categorical(
                "activation", ["relu", "leakyrelu", "elu", "tanh", "swish"]
            ),
            hidden_layers=trial.suggest_int("hidden_layers", 1, 5),
            units=trial.suggest_categorical(
                "units", [8, 16, 32, 64, 128]
            )
        )

        model.fit(X_leaf, y_leaf, epochs=30,
                  batch_size=32, verbose=0)

        y_pred = model.predict(X_leaf).flatten()
        return r2_score(y_leaf, y_pred)

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=n_trials)

    best_params = study.best_trial.params

    model = build_model(
        optimizer=best_params["optimizer"],
        activation=best_params["activation"],
        hidden_layers=best_params["hidden_layers"],
        units=best_params["units"]
    )

    model.fit(X_leaf, y_leaf, epochs=50,
              batch_size=32, verbose=0)

    return model

leaf_ids_train = dt.apply(X_train)

leaf_models = {}
leaf_metrics = {}

MIN_SAMPLES = 50
p = X_train.shape[1]

for leaf_id in np.unique(leaf_ids_train):

    idx = np.where(leaf_ids_train == leaf_id)[0]
    n_leaf = len(idx)

    if n_leaf < MIN_SAMPLES:
        continue

    X_leaf = X_train[idx]
    y_leaf = y_train.iloc[idx]

    model = train_nn_leaf(X_leaf, y_leaf)

    y_leaf_pred = model.predict(X_leaf, verbose=0).flatten()

    r2_leaf = r2_score(y_leaf, y_leaf_pred)
    adj_r2_leaf = 1 - (1 - r2_leaf) * (n_leaf - 1) / (n_leaf - p - 1)

    leaf_models[leaf_id] = model
    leaf_metrics[leaf_id] = {
        "num_samples": n_leaf,
        "r2": r2_leaf,
        "adjusted_r2": adj_r2_leaf
    }

print(f"\nTotal trained leaf-NNs: {len(leaf_models)}")

print("\n LEAF-WISE NN RESULTS")

for leaf_id, stats in leaf_metrics.items():
    print(
        f"Leaf ID: {leaf_id} | "
        f"Samples: {stats['num_samples']} | "
        f"R²: {stats['r2']:.4f} | "
        f"Adjusted R²: {stats['adjusted_r2']:.4f}"
    )

print(f"Total trained leaf-NNs: {len(leaf_models)}")

leaf_ids_test = dt.apply(X_test)

y_hybrid_pred = np.zeros_like(y_test)

for i in tqdm(range(len(X_test))):
    leaf = leaf_ids_test[i]

    if leaf in leaf_models:
        model = leaf_models[leaf]
        y_hybrid_pred[i] = model.predict(X_test[i].reshape(1, -1),verbose=0)[0, 0]
    else:
        # fallback to DT prediction
        y_hybrid_pred[i] = y_dt_test[i]

r2_hybrid = r2_score(y_test, y_hybrid_pred)
adj_r2_hybrid = adjusted_r2(r2_hybrid, len(y_test), X_test.shape[1])

print("\n========== FINAL TEST RESULTS ==========")
print("DT Test R²:", r2_test)
print("DT Test Adjusted R²:", adj_r2_test)
print("DT + NN Hybrid R²:", r2_hybrid)
print("DT + NN Hybrid Adjusted R²:", adj_r2_hybrid)

